apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: kubernetes-test-cf-tls # domain name - tls
spec:
    secretName: kubernetes-test-cf # related to our domain (can be replaced with any domain name)
    duration: 2160h # 90d
    renewBefore: 360h # 15d
    organization:
        - jetstack
    commonName: kubernetes-test.cf # domain name
    dnsNames:
        - kubernetes-test.cf
        - www.kubernetes-test.cf
    issuerRef: 
        name: letsencrypt-prod
        kind: ClusterIssuer
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - kubernetes-test.cf
                - www.kubernetes-test.cf

    
    
    