apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: kubernetes-test-cf-tls # domain name - tls
spec:
    secretName: kubernetes-test-cf # related to our domain (can be replaced with any domain name)
    issuerRef: 
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: kubernetes-test.cf # domain name
    dnsNames:
        - kubernetes-test.cf
        - www.kubernetes-test.cf
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - kubernetes-test.cf
                - www.kubernetes-test.cf